package com.woohood.aihome.model;

public class StudentDemo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_demo.id
     *
     * @mbggenerated Wed Feb 24 11:16:49 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_demo.name
     *
     * @mbggenerated Wed Feb 24 11:16:49 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_demo.age
     *
     * @mbggenerated Wed Feb 24 11:16:49 CST 2016
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_demo.id
     *
     * @return the value of student_demo.id
     *
     * @mbggenerated Wed Feb 24 11:16:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_demo.id
     *
     * @param id the value for student_demo.id
     *
     * @mbggenerated Wed Feb 24 11:16:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_demo.name
     *
     * @return the value of student_demo.name
     *
     * @mbggenerated Wed Feb 24 11:16:49 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_demo.name
     *
     * @param name the value for student_demo.name
     *
     * @mbggenerated Wed Feb 24 11:16:49 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_demo.age
     *
     * @return the value of student_demo.age
     *
     * @mbggenerated Wed Feb 24 11:16:49 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_demo.age
     *
     * @param age the value for student_demo.age
     *
     * @mbggenerated Wed Feb 24 11:16:49 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}